### PR TITLE
Gap species reports

### PR DESCRIPTION
**Pull request by skybristol**
There are still some 0 values in intGapRepro and intGapSeas that should
probably be looked at in the data.

### CODE REVIEW

**Comment by skybristol** [comment]
If you look at the script outputs in the errant values notebook, you'll see that the change in unknown code for reproduction took care of issues with the 7 codes, but there are still some 0 codes showing up in the range data that should either be defined if they are correct or corrected in the underlying data if they were mistakes. Since they are for just a couple of species and HUCs, I'm guessing they were something missed in the data somewhere. I loaded these up into a MongoDB collection for processing from the files that @SGWilliams provided and attached [here](https://www.sciencebase.gov/catalog/item/5951527de4b062508e3b1e79).

Once we get these issues resolved, I will re-run the process that is caching individual range CSVs to the species range items in the collection. If there are any changes in the birds file, someone should output a new file and replace the one on the collection. I'll reprocess it from there so we maintain continuity with source data.

**Comment by nmtarr** [comment]
Matt and Steve looked into those two species' ranges and the zeros are errors that they are going to fix.  I'm going to hand off the task to them.

**Comment by SGWilliams** [comment]
Matt took a look at the db and the spatial output for the two species and advised the following fix written in sql (to remedy our back end range database). @skybristol, let me know if you would rather have a full replacement table identical in format to the initial one.

UPDATE tblRanges_Birds
SET intGapSeas = 3
WHERE (strUC = N'bCOTEx') AND
	  (strHUC12RNG = N'030202040404')

UPDATE tblRanges_Birds
SET intGapRepro = 2, intGapSeas = 3
WHERE (strUC = N'bCOEIx') AND
	  (strHUC12RNG = N'020600020101')

UPDATE tblRanges_Birds
SET intGapRepro = 2, intGapSeas = 3
WHERE (strUC = N'bCOEIx') AND
	  (strHUC12RNG = N'020600020103')

**Comment by skybristol** [comment]
Sorry for not seeing this one earlier. Since we're treating the text files as the source data for these, we need to update the appropriate files and load new versions to the ScienceBase collection. Let me know when that is done, and I'll rebuild the cached CSV tables for the two species.

**Comment by SGWilliams** [comment]
Done. How do you want me to send it? 280 mb file.

**Comment by SGWilliams** [comment]
@skybristol , where/how do you want me to send the updated tblRange_BirdsA-K.csv file? I don't see a SB item for this file.

**Comment by skybristol** [comment]
Hi @SGWilliams. Sorry for missing this question. Go ahead and update the full National_GAP_Birds_Range_Table.txt file here...

https://www.sciencebase.gov/catalog/item/5951527de4b062508e3b1e79

Remove the file that's there now and then upload the new one. Otherwise, it just puts two files on the item with the same name. We're treating those four files attached to the base collection item as the authoritative source for all range data.

**Comment by SGWilliams** [comment]
I just finished replacing the Bird Range Table. This was to correct several erroneous zeros.

**Comment by SGWilliams** [comment]
Well evidently it didn't take. Must have timed out my login before I clicked Save. Trying again now.

**Pull request merged**
